services:
  ocupacao-setores:
    image: sihhsc/gestaoavista:v2
    container_name: ocupacao-setores
    restart: always
    ports:
      - '6003:6003'
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:6003/flask-health-check || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:6003 app:server
